version: '3'

services:

  block_explorer:
    image: enigmampc/block_explorer:develop
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    network_mode: host
    expose:
      - "8008"
    environment:
      - PORT=8008